# Generated by Django 5.2.12 on 2026-03-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_alter_party_options_party_address_party_cnic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date', 'id']},
        ),
        migrations.RenameField(
            model_name='party',
            old_name='jama',
            new_name='total_credit',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='udhaar',
            new_name='total_debit',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='room_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10),
        ),
    ]
