# Generated by Django 5.2.12 on 2026-03-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0003_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='room_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
