# Generated by Django 5.2.12 on 2026-03-30 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0004_remove_party_date_transaction_credit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['name'], 'verbose_name': 'کھاتہ دار', 'verbose_name_plural': 'کھاتہ دار'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date', 'id'], 'verbose_name': 'ٹرانزیکشن', 'verbose_name_plural': 'ٹرانزیکشنز'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='party',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='بیلنس'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='تفصیل / پروڈکٹ نام'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ریٹ'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.TextField(blank=True, null=True, verbose_name='حوالہ'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='V.No'),
        ),
        migrations.AlterField(
            model_name='party',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='پتہ'),
        ),
        migrations.AlterField(
            model_name='party',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شناختی کارڈ نمبر'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='party',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='فون نمبر'),
        ),
        migrations.AlterField(
            model_name='party',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='کل جمع'),
        ),
        migrations.AlterField(
            model_name='party',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='کل نام'),
        ),
        migrations.AlterField(
            model_name='party',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='بیلنس'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='جمع'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='نوٹ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='room_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Room No'),
        ),
    ]
