# Generated by Django 5.2.12 on 2026-03-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0005_alter_party_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='room_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='روم نمبر'),
        ),
    ]
