# Generated by Django 5.2.12 on 2026-03-31 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0006_alter_transaction_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rokad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='روکڑ / Cash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='بیلنس / Balance'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='جمع / Credit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ / Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='نام / Debit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='نوٹ / Note'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='اشیاء / تفصیل'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='تعداد / Qty'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ریٹ / Rate'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.TextField(blank=True, null=True, verbose_name='حوالہ / Reference'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='room_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='روم نمبر / Room No'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='واؤچر نمبر / V.No'),
        ),
    ]
