# Generated by Django 5.2.12 on 2026-04-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0007_transaction_rokad_alter_transaction_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='voucher_no',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='انت / Net Amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bharti',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='بھرتی (KG) / Weight'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='کمیشن / Commission'),
        ),
    ]
