# Generated by Django 5.2.12 on 2026-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0008_remove_transaction_voucher_no_transaction_ant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='دکان کا نام / Shop Name'),
        ),
    ]
