# Generated by Django 5.2.12 on 2026-04-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='trial_end_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trial_start_date',
        ),
    ]
